name: Docker Image Manual

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker images
      run: |
        version=${{ github.event.inputs.version }}
        docker build -t ibombit/lighthouse-puppeteer-chrome:$version-alpine $dir
        docker push ibombit/lighthouse-puppeteer-chrome:$version-alpine