name: Docker Image Manual

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker images
      run: |
        version=${{ github.event.inputs.version }}
        find . -type f -name 'Dockerfile' -exec dirname {} \; | while read dir; do
          if [[ -f "$dir/package.json" && "$dir" == *"$version"* ]]; then
            tag=$(basename "$dir" | sed "s/^v//")
            echo "Building $dir -> ibombit/lighthouse-puppeteer-chrome:$tag-alpine"
            docker build -t ibombit/lighthouse-puppeteer-chrome:$tag-alpine "$dir"
            docker push ibombit/lighthouse-puppeteer-chrome:$tag-alpine
          fi
        done